### PR TITLE
Fix TextField not having is-invalid class

### LINKED ISSUE #29: Invisible errorMessage in TextField
When `errorMessage` is set on a TextField it is invisible as the default CSS style requires the whole input to be marked with the class 'is-invalid' when errors exist. `preact-mdl` doesn't do that so it stays invisible.

### PR DESCRIPTION
**Pull request by TheNeikos**
When errorMessage was set, is-invalid should be added to the container
div. This commit fixes this, and also adds several tests to make sure it
does not interfere with existing options.

fixes #29

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -878,6 +879,11 @@ export class TextField extends MaterialComponent {
 		if (cl) {
 			(field.attributes = field.attributes || {}).class = cl;
 		}
+
+		if (errorMessage) {
+			let classes = (field.attributes = field.attributes || {}).class || "";
+			(field.attributes = field.attributes || {}).class = classes + " is-invalid";
```
Comment (developit) [inline src/index.js]: can you switch this to [setClass()](https://github.com/developit/preact-mdl/commit/a7fbba7dfc1dc290e8e6fc9f1ade917dd5b00440#diff-1fdf421c05c1140f6d71444ea2b27638R26)?

```js
setClass(field.attributes, 'is-invalid', true);
```

Comment (TheNeikos) [reply src/index.js]: Perfect, was looking for something like that

**Comment by TheNeikos** [comment]
@developit Okay, done!

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Released as [2.2.0](https://github.com/developit/preact-mdl/releases/tag/2.2.0)! Thanks :)
